version: '2'
services:
    fortynine-mysql:
        container_name: fortynine-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/fortynine/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=fortynine
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
